cucumber/cucumber-eclipse

cucumber.eclipse.editor/plugin.xml, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinColors.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordScanner.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinPlaceholderRule.java
Addresses Issue #93 
See screenshot:
=> syntax coloring for <placeholders> in scenario outlines

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinReconcilingStrategy.java
=> Remove unintended commercial copyright notice.

cucumber.eclipse.editor/META-INF/MANIFEST.MF, cucumber.eclipse.editor/plugin.xml, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinToggleCommentHandler.java
Simple implementation for https://github.com/cucumber/cucumber-eclipse/issues/45.
=> Add ability to toggle comment to feature file

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/Activator.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinConfiguration.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java
Add Simple Code assistant to suggest keywords base on language.
Open a feature file , move to a blank row and hit content assistant hot key.
=> Add Simple Code assistant to suggest keywords base on language.

README.md
=> Add explanation on how to build and install from source

cucumber.eclipse.editor.test/META-INF/MANIFEST.MF, cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target
=> Add mockito and hamcrest

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordScanner.java
=> Only highlight feature elements that are followed by a colon

cucumber.eclipse.editor/plugin.xml, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/Editor.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/markers/MarkerIds.java
=> Add error marker to editor in case of lexing error

cucumber.eclipse.editor/build.properties, cucumber.eclipse.editor/sample/FeatureTemplate.txt, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/Activator.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/Editor.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinDocumentProvider.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinFormatterUtil.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/template/GherkinSampleTemplate.java
**Sample Feature Definition Template**
----
- Version: 0.0.11.201602191306
- Now a sample feature definition template is available for any blank feature file.
- When you will create new feature file(.feature), your feature file content will always overridden with a sample template which can be used as sample reference as below :
=> Updated version for new feature of Sample Feature Definition Template

cucumber.eclipse.editor.test/META-INF/MANIFEST.MF, cucumber.eclipse.editor.test/pom.xml, cucumber.eclipse.editor/META-INF/MANIFEST.MF, cucumber.eclipse.editor/pom.xml, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/contentassist/CucumberContentAssist.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java, cucumber.eclipse.feature/feature.xml, cucumber.eclipse.feature/pom.xml, cucumber.eclipse.p2updatesite/category.xml, cucumber.eclipse.p2updatesite/pom.xml, cucumber.eclipse.runner/META-INF/MANIFEST.MF, cucumber.eclipse.runner/pom.xml, cucumber.eclipse.steps.integration/META-INF/MANIFEST.MF, cucumber.eclipse.steps.integration/pom.xml, cucumber.eclipse.steps.jdt/META-INF/MANIFEST.MF, cucumber.eclipse.steps.jdt/pom.xml, cucumber.eclipse.targetdefinition/pom.xml, pom.xml
Fixed the Gherkin-Autocompletion feature issues with some improvements
=> Fixed for the Gherkin-Autocompletion feature issues with some improvements

cucumber.eclipse.editor.test/META-INF/MANIFEST.MF, cucumber.eclipse.editor.test/pom.xml, cucumber.eclipse.editor/META-INF/MANIFEST.MF, cucumber.eclipse.editor/pom.xml, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/wizard/NewStepDefFileWizardPage.java, cucumber.eclipse.feature/feature.xml, cucumber.eclipse.feature/pom.xml, cucumber.eclipse.p2updatesite/category.xml, cucumber.eclipse.p2updatesite/pom.xml, cucumber.eclipse.runner/META-INF/MANIFEST.MF, cucumber.eclipse.runner/pom.xml, cucumber.eclipse.steps.integration/META-INF/MANIFEST.MF, cucumber.eclipse.steps.integration/pom.xml, cucumber.eclipse.steps.jdt/META-INF/MANIFEST.MF, cucumber.eclipse.steps.jdt/pom.xml, cucumber.eclipse.targetdefinition/pom.xml, pom.xml
Fixed for Cucumber-File-Wizard Issue
=> Fixed for Cucumber-File-Wizard Issue

index.html
=> Fix update site url

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/contentassist/CucumberContentAssist.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java
=> Suggest step keywords based on language

README.md, cucumber.eclipse.editor.test/META-INF/MANIFEST.MF, cucumber.eclipse.editor.test/pom.xml, cucumber.eclipse.editor/META-INF/MANIFEST.MF, cucumber.eclipse.editor/plugin.xml, cucumber.eclipse.editor/pom.xml, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/contentassist/CucumberContentAssist.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/StepMatcher.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberUserSettingsPage.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/ICucumberPreferenceConstants.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/CucumberAnnotation.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/StepDefinitions.java, cucumber.eclipse.feature/feature.xml, cucumber.eclipse.feature/pom.xml, cucumber.eclipse.p2updatesite/category.xml, cucumber.eclipse.p2updatesite/pom.xml, cucumber.eclipse.runner/META-INF/MANIFEST.MF, cucumber.eclipse.runner/pom.xml, cucumber.eclipse.steps.integration/META-INF/MANIFEST.MF, cucumber.eclipse.steps.integration/pom.xml, cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/Step.java, cucumber.eclipse.steps.jdt/META-INF/MANIFEST.MF, cucumber.eclipse.steps.jdt/pom.xml, cucumber.eclipse.targetdefinition/pom.xml, pom.xml
Fixed the Issue #145. Updated plugin with new version '0.0.16.201703160952' for implementation
of the new feature i.e. "Reusing Of Step-Definitions From External Class-Path
Dependencies(JAR/POM...etc)".
=> Updated plugin with the new feature "Reusing Of Step-Definitions From External Class-Path Dependencies(JAR/POM...etc)"

cucumber.eclipse.editor.test/META-INF/MANIFEST.MF, cucumber.eclipse.editor.test/pom.xml, cucumber.eclipse.editor/META-INF/MANIFEST.MF, cucumber.eclipse.runner/META-INF/MANIFEST.MF, cucumber.eclipse.steps.integration/META-INF/MANIFEST.MF, cucumber.eclipse.steps.jdt/META-INF/MANIFEST.MF, pom.xml
Once this is approved, I'll work on deployment to update-site.
=> Incrementing to new Release Version (0.0.17)

cucumber.eclipse.editor/pom.xml, cucumber.eclipse.feature/feature.xml, cucumber.eclipse.feature/pom.xml, cucumber.eclipse.p2updatesite/category.xml, cucumber.eclipse.p2updatesite/pom.xml, cucumber.eclipse.runner/pom.xml, cucumber.eclipse.steps.integration/pom.xml, cucumber.eclipse.steps.jdt/pom.xml, cucumber.eclipse.targetdefinition/pom.xml
Some stuff was open when I committed and I will accept the shameful responsibility for breaking a release in a silly way. This time I did it right though.
I'll even include evidence:
=> Adding missing build changes for release 0.0.17

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/JDTStepDefinitions.java
Updated 'JDTStepDefinitions' by commenting some lines in order to avoid unnecessary logs
=> Minor update of 'JDTStepDefinitions'

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/tests/GherkinFormattingStrategyTest.java, cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/tests/GherkinTestFixtures.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinFormatterUtil.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PrettyFormatter.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferenceInitializer.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferencePage.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/ICucumberPreferenceConstants.java
Add a new preference that allows the user to change the style of white-space used by the autoformatter.  The user can toggle between 2 spaces, 4 spaces, or tabs.  
Closes https://github.com/cucumber/cucumber-eclipse/issues/279
=> Add Preference for Changing Autoformatter Indentation Style

cucumber.eclipse.editor/META-INF/MANIFEST.MF, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/Editor.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/markers/StepCreationMarkerResolutionGenerator.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/ExtensionRegistryStepProvider.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/JDTStepDefinitions.java, cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/IStepDefinitions.java
- fixes Issue #287 
- fixes #281 since it schedules the loading of step defs in the background, the steps are highlighted as soon as the loading process is done but the editor opens instantly
=> Fix Issue 287 / 281

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/JDTStepDefinitions.java
=> check if the latest opened feature file is in a closed project

continuous-deployment/prepare-deploy
=> Closes #322 fix eclipse update sites github repository URLS

cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaStepDefinitionsProvider.java
Before, an exception would be thrown.
A file outside the classpath can be safely ignored.
Sorry about the indentation, I added a try{...}catch(JavaModelException){} around the method body.
=> handle java files not in classpath

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/builder/CucumberGherkinBuilder.java
when building incrementally, first run a quick scan of the resource delta to see if we want to do a full build instead.
=> better detect when full build is required

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/builder/CucumberGherkinBuilder.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/GlueRepository.java, cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/StepDefinition.java, cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/marker/MarkerFactory.java
This is the next step in resolving Issue #291 
- moving the "matches" away from the step definition and put the logic into the project related Glue Respository
=> Issue #291 move expression parsing from StepDefinition to GlueRepository

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/GlueRepository.java, cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/GlueStorage.java
The GlueRepository now tries to adapt the project to an ExpresionFactory and uses this instead of a custom constructed one.
=> Issue #291 try to get an adapted ExpresionFactory by project

cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/filter/SameLocationFilter.java
Check that the resource is not null and has a parent
=> Issue #344 - NPE in SameLocationFilter with current Snapshot

cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/ResourceHelper.java
=> Fix isse #355

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/UniversalStepDefinitionsProvider.java
When two projects reference each other Cucumber's step builder stumble upon an infinite and lead to a SO that forces the user to exit the workbench.
This commit prevents such an issue by adding a cache that avoids analyzing a project more than once.
I tested the code manually and can state that issue #360 is solved. However, since there are no tests on the `UniversalStepDefinitionsProvider` class I cannot ensure that this PR does not introduce any regression. That being said, the changes are straightforward so regressions are very unlikely.
Please tell me if more tests/changes are required before merging this PR.
=> Issue #360 Prevent StackOverflowError on circular project dependencies

cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaStepDefinitionsProvider.java
Fix #391 
Methods using annotations from the `io.cucumber` package were not taken into account if the class comes from an external dependency. Only those in the `cucumber.api` package were.
The `cucumber.api` package is deprecated in favor of` io.cucumber`. Both are kept for backward compatibility.
=> fix #391 - step definition using annotations from io.cucumber are not detected

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/builder/CucumberGherkinBuilder.java
- queue up gherkin files to be linked with step definitions
- perform step linking for each file in the queue
- cancel the build if an interrupt occurs; the user wants to do something
Missing from this solution:
- continue building where we left off?
- builder is interrupted by user, may not start again until triggered?
- interrupt notifications occur when saving files etc
- on large projects a full build can take more than 15 mins
- the builder should not prevent interaction with eclipse during the build
This change makes #371 a little less unbearable for large projects
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds new behaviour)
_Remember to add an entry to the relevant section of CHANGELOG.md as part of this pull request._
_If your …
=> comply with interrupted notifications

.github/workflows/maven.yml, .gitignore, .mvn/extensions.xml, pom.xml
Currently the build is wrecked due to outdated build dependencies.
=> Update the build to Tycho 3.0

io.cucumber.eclipse.editor/META-INF/MANIFEST.MF, io.cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target
Bumped version of Apache Commons Text to 1.10 to mitigate text4Shell vulnerability exposure 
Remove exposure to RCE vulverability
----
=> Update Apache Commons Text Version

examples/java-datatable/.classpath, examples/java-datatable/.project, examples/java-datatable/pom.xml, examples/java-datatable/src/main/java/cucumber/examples/datatable/Animals.java, examples/java-datatable/src/main/java/cucumber/examples/datatable/Cat.java, examples/java-datatable/src/main/java/cucumber/examples/datatable/Elephant.java, examples/java-datatable/src/test/java/cucumber/examples/DatatableSteps.java, examples/java-datatable/src/test/resources/cucumber/examples/datatable.feature
Example with DataTables.
The Idea is to build a new feature, that relates the DataTable Keys with some Parameter in Steps.
----
=> DataTable Example for new relation functionality

examples/java-datatable/.classpath, examples/java-datatable/.settings/org.eclipse.core.resources.prefs, examples/java-datatable/.settings/org.eclipse.jdt.core.prefs, examples/java-datatable/pom.xml, io.cucumber.eclipse.product/cucumber-eclipse.product, io.cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target
- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
----
=> Include m2e in the product and fix the example to use java 17

.mvn/maven.config, io.cucumber.eclipse.editor/META-INF/MANIFEST.MF, io.cucumber.eclipse.java/META-INF/MANIFEST.MF, io.cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target
- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
----
=> Update to latest Eclipse Release

.mvn/maven.config, io.cucumber.eclipse.feature/feature.xml, io.cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target, pom.xml
Update to latest Eclipse / Tycho release, include all dependencies
See https://github.com/cucumber/cucumber-eclipse/issues/507
- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMP …
=> Update to latest Eclipse / Tycho release, include all dependencies

.github/workflows/maven.yml
- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
----
=> Update to use v2.x branch in CI

.github/workflows/maven.yml, .mvn/maven.config, io.cucumber.eclipse.editor/.classpath, io.cucumber.eclipse.editor/.settings/org.eclipse.jdt.core.prefs, io.cucumber.eclipse.editor/META-INF/MANIFEST.MF, io.cucumber.eclipse.feature/feature.xml, io.cucumber.eclipse.java.plugins/.classpath, io.cucumber.eclipse.java.plugins/.settings/org.eclipse.jdt.core.prefs, io.cucumber.eclipse.java.plugins/META-INF/MANIFEST.MF, io.cucumber.eclipse.java/.classpath, io.cucumber.eclipse.java/.settings/org.eclipse.jdt.core.prefs, io.cucumber.eclipse.java/META-INF/MANIFEST.MF, io.cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target, pom.xml
- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
----
=> Update to new 3.0.0-SNAPSHOT version

io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/codemining/CucumberRunCodeMiningProvider.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/contentassist/GherkinContentAssistProcessor.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/debug/GherkingGroupValue.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/debug/GherkingStepDefinitionValue.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/debug/GherkingStepStackFrame.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/debug/GherkingToggleBreakpointsTarget.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/document/GherkinEditorDocument.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/document/GherkinMessageHandler.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/document/GherkinStream.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/document/TestStepEvent.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/hyperlinks/IStepDefinitionOpener.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/hyperlinks/StepHyperlink.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/hyperlinks/StepHyperlinkDetector.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/launching/CucumberFeatureLaunchShortcut.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/launching/EnvelopeListener.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/launching/ILauncher.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/marker/MarkerFactory.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/testresults/CucumberTestRunnerClient.java, io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/validation/GherkinSyntaxValidator.java, io.cucumber.eclipse.feature/feature.xml, io.cucumber.eclipse.java.plugins/META-INF/MANIFEST.MF, io.cucumber.eclipse.java.plugins/src/io/cucumber/eclipse/java/plugins/CucumberEclipsePlugin.java, io.cucumber.eclipse.java.plugins/src/io/cucumber/eclipse/java/plugins/Jackson.java, io.cucumber.eclipse.java.plugins/src/io/cucumber/eclipse/java/plugins/MessageEndpoint.java, io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/launching/CucumberRuntimeLauncher.java, io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/launching/MessageEndpointProcess.java, io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/runtime/CucumberRuntime.java, io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/steps/JavaStepDefinitionOpener.java, io.cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target
This includes the required changes to compile with Cucumber 7 API.
More cleanup and adjustments are required but can go into separate PRs. 
The work on this was gently sponsored by [Katalon](https://katalon.com/).
=> Adapt to Cucumber 7 API

io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/validation/GlueJob.java
Currently one can _configure_ the glue filters but they are effectively ignored when matching the glue code. This is because we do not forward them to the runner instance we use to detect the glue code.
This now forwards the settings (after some cleanups) to the job
=> Forward the glue path from the preferences to the glue job

io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/runtime/CucumberRuntime.java
As a workaround for 
- https://github.com/cucumber/cucumber-jvm/issues/3037 
Fix https://github.com/cucumber/cucumber-eclipse/issues/532
=> Supply own eventbus to use a custom UUID generator
