cucumber/cucumber-eclipse

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PopupMenuFindStepActionDelegate.java

I wondered why the <kbd>Find Step</kbd> Feature did not worked for me and noticed that it was caused by a `NullPointerException`...

fix NPE when languageCode is null and just default to EN

---

cucumber.eclipse.editor/plugin.xml
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinColors.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordScanner.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinTagRule.java

added syntax coloring for `@tags` and do not confuse them with email addresses.
see screen grap...

syntax coloring for `@tags`

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinFormatterUtil.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PrettyFormatter.java

addresses #85 
The Pretty Printing was done via `gherkin.formatter.PrettyFormatter` which is part of [cucumber/gherkin](https://github.com/cucumber/gherkin). This pull request copied the original PrettyFormatter and added the missing feature to right-align numeric values in tables.

Rightalign numeric values

---

cucumber.eclipse.editor/plugin.xml
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/Activator.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinFormatterUtil.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PrettyFormatter.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferenceInitializer.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferencePage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/ICucumberPreferenceConstants.java

Adds some new formatting options to the Gherkin Formatter, that are currently pending in a separat PR (https://github.com/cucumber/gherkin/pull/331).
- allow for project specific preferences via property page

Pretty formatter options

---

cucumber.eclipse.editor.test/META-INF/MANIFEST.MF

Made cucumber.eclipse.editor.test a fragment. This is a common way to separate test from production code while still being able to unit test non public classes/methods.

Fix tests failing during build

---

cucumber.eclipse.targetdefinition/cucumber.eclipse.targetdefinition.target
cucumber.eclipse.targetdefinition/pom.xml
pom.xml

Make it possible for contributors to develop in their Eclipse version of choice. This approach is the only way to share the same target platform configuration between Tycho and Eclipse. (see: https://wiki.eclipse.org/Tycho/Target_Platform)

Add target definition file

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarkerTest.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java

Syntax error and step missing markers are currently being created with a line number attribute one lower than expected (i.e. a marker on line 1 shows "line 0" in the location column of the Problems or Markers views).
This PR resolves this issue.

Correct line numbers of error/missing step markers.

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinConfiguration.java

The Gherkin editor formatter (Ctrl+Shift+F in editor) formats tabs to have a width of 2, but a tab key in the editor inserts a tab of the default width.
This PR sets the editor tab width to 2 to bring it in line with the formatter.

Set editor tab width to 2 to bring in line with formatter.

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/GherkinModelTest.java
cucumber.eclipse.editor/META-INF/MANIFEST.MF
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/Editor.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinModel.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinOutlinePage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinReconcilingStrategy.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PositionedElement.java

This PR adds a (very) simple outline view for the Gherkin editor as described in issue #55.
Scenarios/scenaro outlines and step nodes are added to the content outline tree. Selecting a node will move the caret in the Gherkin editor to the relevant node.

Outline view

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/StepMatcherTest.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/StepMatcher.java

1. There a exception thrown  ```languageCode = languageCode.toLowerCase();```,because I18n use exactly case. eg: ```zh-CN,zh-TW```.
2. Line 60 ```return Pattern.compile((sb.append(") (.*)$").toString()));``` append a extra space will cause step match failure in CJK language. So use getStepKeywords and quote it.
3. Add a extra test case ,and it passed.

Fix marker not found when in CJK language.

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java

This fixes a problem I was seeing with long waits to open a feature file in a project with many step definitions. Changed to look up all the steps in the project only once (when a file is loaded) and store that result instead of doing it every time a step is parsed.

GherkinErrorMarker Optimization

---

cucumber.eclipse.editor/META-INF/MANIFEST.MF
cucumber.eclipse.editor/pom.xml
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/contentassist/CucumberContentAssist.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java
cucumber.eclipse.steps.jdt/META-INF/MANIFEST.MF
cucumber.eclipse.steps.jdt/pom.xml

*note:* the "|" (pipe character) in the description describe where the cursor is in the editor at the moment I press `Ctrl+Space.`
* **`Given I|`** auto-completes to `Given I want to write a step with precondition`
* It's **correct**
* **`Given I want|`** shows **No Step Definition Found**
* *The issue:* I want to auto-complete to **Given I want to write a step with precondition**
* **`Given I want |`** auto-completes to `Given I want I want to write a step with precondition`
* *The issue:* this sentence has no meaning and does not exist.
I want to auto-complete to "Given I want to write a step with precondition"
* **`Given I| made a slight mistake by not knowing the sentence exactly`** auto-completes to `Given I want to write a step with preconditionmade a slight mistake by not knowing …

Better Gherkins autocompletion

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/StepDefinitions.java

Current implementation of plugin looks for steps only in the same project in which feature is located. But sometimes step definitions could be located in projects added as dependencies to current one. So, there is a search for step definitions in these projects as well added in this PR.
Also minor improvement for 'Step does not have a matching glue code' warning message is added. It will be useful to have also step name in it "Step 'step name' does not have a matching glue code"

Fixed issue with steps from dependency projects incorrectly marked as not having matching code

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PopupMenuFindStepFormatter.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/PopupMenuFindStepHandler.java

1. Added new Gherkin formatter for FindStep popup menu handler, which takes step name for selected line and in case step belongs to scenario outline - scans all examples and generates different step string with replaced variables for each example. FindStep popup menu handler now looks for step definition for any example string (with replaced variables)
2. Same logic implemented for error marker: now if steps belong to scenario outline, formatter goes over all examples, replaces all variables and adds warning for each example, in which step with replaced variables does not match any step definition.
Issue https://github.com/cucumber/cucumber-eclipse/issues/159 should be fixed now

Fix for step matching in scenario outlines

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/StepMatcherTest.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/StepMatcher.java

I found a more generic way of matching outline parameters.
The current code replaces any \<parameter\> in a step with 0, hoping for the cucumber step regular expressions to match. It is already noted in the code that this is a temporary fix - the ideal solution is to read the outline examples and substitute the first parameter values in order to make a tested step match. However this is unreasonable work.
The inverse solution to this, is to modify the cucumber regexp dynamically during matching to become lenient to \<parameter\> matching. Hence, all \<parameter\> are replaced with generic \<p\> on the gherkin step, and on the regexp all matching groups e.g. (\d+), (.\*), (one|two) have an additional \<p\>| inserted.
i.e
(\d+) -> (\<p\>|\d+)
(.\*) -> (\<p\>|.\*)
(one|two) -> …

Generic outline <parameter> matching to any cucumber regexp

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarkerTest.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinConfiguration.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinErrorMarker.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferenceInitializer.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferencePage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/ICucumberPreferenceConstants.java

Please bear with me as I have not worked with Eclipse plugins before... or Java at all for a few years.
This pull request introduces a preference to turn off Step matching and content assist. Useful for people who want the good stuff for .feature file editing, but work with other languages for implemented steps such as Python.
I couldn't determine whether the standard in this project is tabs or spaces. I found mostly tabs when browsing the source code so I went for that.
Comments?

Introduce plugin preference to turn off Step matching

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/wizard/NewStepDefFileWizard.java

Attempting to fix problem where quotes are not generated for step definitions when the new step definition file wizard is used and example definitions generated using check boxes.

Adjusted the NewStepDefFileWizard to generate with quotes for annotations

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/util/Utils.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/wizard/NewStepDefFileWizardPage.java

Eclipse by default uses forward slashes in both windows and linux machine in the new file creation wizards and does not use windows file path. In #192 a validation check was added for windows such that backward slashes would not throw validation error. However, this introduced bug #196. This is because eclipse works with forward slashes only and the issue was with the way the generated file path in NewStepDefFileWizard was made to be os specific.
To fix this, I removed the validation check which checks for windows and in the section where the file path is generated, I used toString() instead of toOSString(). This change will fix both issues - #192 and #196.
Let me know if this is ok. I have tested it on my local windows and linux installations.

Fix#192, #196 - NewStepDefFileWizard Source Folder path issue

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferenceInitializer.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberPreferencePage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/CucumberUserSettingsPage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/preferences/ICucumberPreferenceConstants.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/JDTStepDefinitions.java

Added a preference to limit the search scope for step implementation to the package (and the sub-package) for the location of the feature file.
Consider the following setup:
```
\- src/test/java
\- cucumber/
\- test/
\- a/
|  +- a.feature
|  +- TestARunner.java
|  \- TestASteps.java
\- b/
+- b.feature
+- TestBRunner.java
\- TestBSteps.java
```
By default, `cucumber-eclipse` will match steps in `a.feature` with implementations in `TestBSteps.java` (and vice versa).
With this new preference, steps in `a.feature` will only be matched against implementations in `cucumber.test.a` (and it's sub-packages, if it had any).

Only match step implementation in same package as feature file

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/JDTStepDefinitions.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/StepDefinitions.java

This fixes the problem that changes in step implementations isn't
reflected in the feature file. Before one had to close/open the feature
file for it to be updated, either when adding or removing matching step
implementations.

Changes in step implementation is reflected in feature file

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/contentassist/CucumberContentAssist.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordsAssistProcessor.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/ExtensionRegistryStepProvider.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/jdt/JDTStepDefinitions.java
cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/IStepDefinitions.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaParser.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/MethodDefinition.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/StepDefinitions.java

Currently Step-Definitions Codecompletion only works with English Language (Given, ...) but not with other Languages (e.g. German "Angenommen"...) this pull request fixes this by not rely on hard coded regular expressions but checking the language specific keywords directly.

Don't use hardcoded keywords to support other languages

---

README.md

The readme link was pointing to an ant configuration to provide a list of dependencies to the user. 
- Changed the link to point to official documentation
- Updated the related description.

#260: Fixed readme links to point to cucumber documentation.

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordScanner.java

Simple change to help reduce the number of false-positives for the string-literal syntax highlighting in the Cucumber Editor.  
Current Highlighting (before the change):
New Highlighting (after the change):
Fixes https://github.com/cucumber/cucumber-eclipse/issues/83 and https://github.com/cucumber/cucumber-eclipse/issues/91

Fix string literal syntax highlighting

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/StepHyperlinkTest.java
cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/StepMatcherTest.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinConfiguration.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/StepHyperlink.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/StepHyperlinkDetector.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/StepMatcher.java

Hello, 
This PR allows to use <kbd>CTRL</kbd>+<kbd>click</kbd> on a step to jump into its definition, as <kbd>F3</kbd>. (#204)
**Known limitation**
As #285, only built-in cucumber expressions (with built-in parameter types, or with regular expressions) are supported. The plugin lacks `ParameterType` detection for now.
An other example with lambdas

Fix #204. Go to step definition from a feature file with CTRL+click

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/GherkinModelTest.java

This is just a new test to ensure the `GherkinModel` supports i18n feature.
I added it when I tried to reproduce the issue #282

Add test about i18n support

---

cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaStepDefinitionsProvider.java

The step definitions provider for Java uses the Eclipse JDT search engine to detect step definitions from the classpath.
If the search engine failed, the builder should continue silently. Thus, the step definitions from the classpath will be probably incomplete but it is less bad than return nothing.
Fix #313

Cucumber builder should continue the step definitions scan even if the search engine failed

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/nature/CucumberProjectNature.java

Fixes #328 
The gherkin builder was simply forgotten.
Remove it in the same time as the builder for step definitions.
More remove the `Set` used to filter builders, since this one lost the builders order.

Remove the cucumber gherkin builder when a project lost the cucumber nature

---

cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/StepDefinition.java

Fix #336 
This PR removes an unnecessary parsing of cucumber expression when using <kbd>CTRL</kbd>+<kbd>clic</kbd>.
This one threw a `CucumberExpressionException` when creating the `StepDefinition` object. In this case, the step definition is used to create an hyperlink which does not require to evaluate the expression. More, this evaluation was redundant since it is also done by `matches` method.
With this fix, it is possible to jump to step definition like this one.

Remove unnecessary parsing of the step expression

---

cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/editors/StepHyperlinkTest.java
cucumber.eclipse.editor.test/src/main/java/cucumber/eclipse/editor/steps/StepDefinitionsRepositoryTest.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/builder/CucumberGherkinBuilder.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/contentassist/CucumberContentAssist.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/jumpto/JumpToStepDefinition.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/jumpto/StepHyperlinkDetector.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/BuildStorage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/GlueRepository.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/GlueStorage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/StepDefinitionsRepository.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/StepDefinitionsStorage.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/StorageHelper.java
cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/steps/UniversalStepDefinitionsProvider.java
cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/AbstractStepDefinitionsProvider.java
cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/ExpressionDefinition.java
cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/StepDefinition.java
cucumber.eclipse.steps.integration/src/main/java/cucumber/eclipse/steps/integration/marker/MarkerFactory.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaStepDefinitionOpener.java
cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaStepDefinitionsProvider.java

This is a refactoring in preparation of issue #291 it makes the following changes
1. StepDefintion is now a final, unmodifiable class, so it is safe to cache and reference instances of this class
2. StepDefinition now has a ExpresionDefinition (what we will need later to support #291 
3. Serialization was changed, so that the StepDefiniton/ExpresionDefintion must not know how serialization works
4. Error reporting and handling has been improved, so you can recover from broken/old/... serialization files

Preparation for Issue291 improve stepdefinition data model

---

cucumber.eclipse.steps.jdt/src/main/java/cucumber/eclipse/steps/jdt/JavaStepDefinitionsProvider.java

As discussed in #368 ; First time developing on a plugin; Not tested yet but code seems straight forward. What's the flow needed to try this out?

Fix 368 by also matching `io.cucumber` annotations and interfaces

---

.travis.yml

The build [travis#91](https://travis-ci.org/cucumber/cucumber-eclipse/jobs/579786321) failed due to a change of the default Ubuntu distribution from trusty to xenial.
This last have an incompatibility issue with the installation script of the oraclejdk. Thus, the following error occurs during the build:
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" …
```

Fix travis build error due to incompatibility between the oraclejdk and ubuntu xenial

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/editors/GherkinKeywordScanner.java

This pull request fixes #378 
The `GherkinKeywordScanner` class  is responsible of the detection of Gherkin keywords for their highlight. It describes the string object as a token starting by `[space]"` or `[space]'` and ending by `"[space]` or `'[space]`. And so it did not recognize properly the sample describe in #378

Fix string highlight in Gherkin files

---

cucumber.eclipse.editor/src/main/java/cucumber/eclipse/editor/builder/CucumberGherkinBuilder.java

Fix #382 
As describe in the sample of #382, the steps from a scenario outline are not detected if the examples are not written.
In case of a scenario outline, the step are validated only when parsing the examples, even if the step does not use one of them.
This fix allows to find glue of a step from a scenario outline without reading the example. But in the case of a scenario outline, we ca not mark as `unmatch` if no step definition was found. Indeed, if a example is used, the values can help to match a step definition.

The steps from scenario outline are not detected 

---

cucumber.eclipse.editor/META-INF/MANIFEST.MF
cucumber.eclipse.editor/build.properties
cucumber.eclipse.editor/css/e4_dark_cucumber.css
cucumber.eclipse.editor/plugin.xml

Fixes #417.
Below are the results with the current set of colours - as you can see, it's now much more readable!

Add editor preferences for Eclipse's Dark theme

---

cucumber.eclipse.editor/plugin.xml

This fixes  #423 by adding a filter to the extension point.

Enable Glue Code Options only when selecting a project

---

.github/workflows/maven.yml

Use the [cache built into](https://github.com/actions/setup-java#caching-maven-dependencies) the `actions/setup-java` Github Action.
Speed up the build. The existing cache doesn't seem to work, and adds complexity to the build script that maybe we don't need anymore.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
I want to just let it run and see if it improves the build time.
----

Try using actions/setup-java cache

---

examples/java-datatable/src/main/java/cucumber/examples/datatable/AnimalValidator.java
examples/java-datatable/src/test/resources/cucumber/examples/datatable.feature
io.cucumber.eclipse.editor/plugin.xml
io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/marker/MarkerFactory.java
io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/runtime/CucumberRuntime.java
io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/validation/CucumberGlueValidator.java

Currently it is only possible to validate the glue on execution but it some cases it would be useful to have some prevalidation.
This adds support for specify validation plugins in the glue code that are executed as part of the parsing of document and show up as errors immediately on save.
https://github.com/cucumber/cucumber-eclipse/assets/1331477/bf94219f-b131-4c56-9600-7f7db052cab9

Add support for validation plugins from the project

---

io.cucumber.eclipse.editor/src/io/cucumber/eclipse/editor/marker/MarkerFactory.java

Currently if one fixes all validation errors (or disables the validator)
the old errors stay permanently.
This deletes all markers if there are currently no errors or validators.

Delete previous validation errors if there are none

---

.mvn/maven.config
io.cucumber.eclipse.java/META-INF/MANIFEST.MF
io.cucumber.eclipse.java/src/io/cucumber/eclipse/java/properties/CucumberJavaBackendProperties.java

CucumberJavaBackendProperties#setEnabled does not do what it claims and instead of just fetches the current value as a result of C&P error.
This now fixes the method to correctly update the value, beside that it exports all packages (as internal) to allow access for other plugins that want to change java settings programmatically.

Fix wrong CucumberJavaBackendProperties#setEnabled method
